# Build stage: compiles the Spring Boot application using Maven
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app

# Copy Maven wrapper and configuration first to leverage Docker layer caching
COPY pom.xml mvnw .mvn/ /app/
RUN chmod +x mvnw

# Copy the rest of the source tree (sources, resources, configs)
COPY . /app

# Build the executable jar
RUN ./mvnw clean package -DskipTests

# Runtime stage: run the built jar on a lightweight JDK image
FROM amazoncorretto:21-alpine-jdk
WORKDIR /app

# Copy the boot jar generated by Maven
COPY --from=build /app/target/*SNAPSHOT.jar /app/app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
